os: linux
sudo: required
dist: trusty
language: c

compiler:
  - clang

branches:
  only:
    - coverity

before_install:
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJvf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..
  - if [ "${CC}" = "gcc" ]; then pip install --user codecov; export CFLAGS="-coverage"; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dOIHA+29WzdS1GPm2A/2osTIm4GAGP+OCP/CoYN8gZ4W9yxHKY+noJevDtPw+KDQ5wgBKEcqPnLA1gVI6PeRLdxjHpWULzaH9GZsjktK2YNJJkO2kw2tBrXp09ak4jczokaYcdOM1pfXFbTPYRpDHyd4nS8QvFM4nev7xg87zvU="

addons:
  coverity_scan:
    project:
      name: "CESNET/libyang"
    notification_email: rkrejci@cesnet.cz
    build_command_prepend: "cmake .; make clean"
    build_command:   "make"
    branch_pattern: coverity

script:
  # do nothing, everything here is done in coverity addon
  - true

